# You'll need to activate pipelines for this file to have any effect
# in gitlab, go to Settings -> General -> Permissions -> Pipeline

stages:
 - test
 - deb
 - deploy

test-for-jessie: &test-for-jessie
  image: debian:jessie
  stage: test
  tags:
    - docker
  services:
    - mysql:5.5
    - postgres
  variables:
    RAILS_ENV: test
    MYSQL_ROOT_PASSWORD: uheiN4pe
    MYSQL_DATABASE: g5kapi_test
    MYSQL_USER: g5kapi
    MYSQL_PASSWORD: Pe9IeCei
    POSTGRES_USER: oar
    POSTGRES_PASSWORD: oar
    POSTGRES_DB: oar2_test
  script:
    - apt update
    - apt install -y postgresql-client git bundler rake libxml2-dev libxslt-dev libicu-dev libmysqlclient-dev libpq-dev nodejs
    - bundle install --path vendor/bundle
    - bundle exec rake db:migrate
    - bundle exec rake db:oar:seed
    - bundle exec rspec spec/
  coverage: '/\(\d+.\d+\%\) covered/'

test-for-stretch:
  <<: *test-for-jessie
  image: debian:stretch
  services:
    - postgres
    - mariadb:10.1
  script:
    - apt update
    - apt install -y postgresql-client git bundler rake libssl-dev libxml2-dev libxslt-dev libicu-dev default-libmysqlclient-dev libpq-dev nodejs
    - "sed -i -e 's/host: mysql/host: mariadb/' config/database.yml"
    - bundle install --path vendor/bundle
    - bundle exec rake db:migrate
    - bundle exec rake db:oar:seed
    - bundle exec rspec spec/
  
deb-for-jessie: &deb-for-jessie
  image: debian:jessie
  stage: deb
  tags:
  - docker
  script:
  - apt-get update
  - apt-get install -y lsb-release git git-core bundler rake libssl-dev libxml2-dev ruby-dev libicu-dev build-essential libmysqlclient-dev libxslt-dev libpq-dev nodejs curl pkg-config
  - bundle install --path vendor/bundle
  - bundle exec rake package:build:debian 
  artifacts:
    paths:
    - pkg/g5k-api*.deb
    expire_in: '1 day'

deb-for-stretch:
  <<: *deb-for-jessie
  image: debian:stretch
  script:
  - apt-get update
  - apt-get install -y lsb-release git git-core bundler rake libxml2-dev ruby-dev libicu-dev build-essential default-libmysqlclient-dev libxslt-dev libpq-dev nodejs curl pkg-config
  - bundle install --path vendor/bundle
  - bundle exec rake package:build:debian

.push-packages-script: &push-packages-script |
  git tag --points-at $CI_COMMIT_REF_NAME #debug output
  IS_TAGGED=$(git tag --points-at $CI_COMMIT_REF_NAME)
  if [ -n "$IS_TAGGED"  ] ; then
    echo "Request to push for debian version ${TARGET_DEBIAN_VERSION} for branch ${TARGET_G5K_API_VARIANT}"
    g5k-deploy-files --files 'pkg/g5k-api_*.deb' --directory deb/g5k-api/${TARGET_DEBIAN_VERSION}/${TARGET_G5K_API_VARIANT}
  else
    echo "commit is not tagged"
    exit 1
  fi
  
  
push-jessie-package-v3: &push-jessie-package-v3
  stage: deploy
  when: manual
  # tags must be 'packages' so that we use the runner on packages.grid5000.fr
  tags:
    - packages
  only: # we only execute this job for tagged commits on the master branch
    - master
  dependencies:
    - deb-for-jessie
  variables:
    TARGET_DEBIAN_VERSION: jessie
    TARGET_G5K_API_VARIANT: v3
  script:
    - *push-packages-script

push-jessie-package-devel: &push-jessie-package-devel
  <<: *push-jessie-package-v3
  variables:
    TARGET_DEBIAN_VERSION: jessie
    TARGET_G5K_API_VARIANT: devel
  only: 
    - devel
    
push-stretch-package-v3:
  <<: *push-jessie-package-v3
  dependencies:
    - deb-for-stretch
  variables:
    TARGET_DEBIAN_VERSION: stretch
    TARGET_G5K_API_VARIANT: v3

push-stretch-package-devel:
  <<: *push-jessie-package-devel
  dependencies:
    - deb-for-stretch
  variables:
    TARGET_DEBIAN_VERSION: stretch
    TARGET_G5K_API_VARIANT: devel
  
