# You'll need to activate pipelines for this file to have any effect
# in gitlab, go to Settings -> General -> Permissions -> Pipeline

stages:
 - test
 - deb
 - deploy

test-for-jessie: &test-for-jessie
  image: debian:jessie
  stage: test
  tags:
    - docker
  services:
    - mysql:5.5
    - postgres
  variables:
    RAILS_ENV: test
    MYSQL_ROOT_PASSWORD: uheiN4pe
    MYSQL_DATABASE: g5kapi_test
    MYSQL_USER: g5kapi
    MYSQL_PASSWORD: Pe9IeCei
    POSTGRES_USER: oar
    POSTGRES_PASSWORD: oar
    POSTGRES_DB: oar2_test
  script:
    - apt update
    - apt install -y postgresql-client git bundler rake libxml2-dev libxslt-dev libicu-dev libmysqlclient-dev libpq-dev nodejs
    - bundle install --path vendor/bundle
    - bundle exec rake db:migrate
    - bundle exec rake db:oar:seed
    - bundle exec rspec spec/
  coverage: '/\(\d+.\d+\%\) covered/'

test-for-stretch:
  <<: *test-for-jessie
  image: debian:stretch
  services:
    - postgres
    - mariadb:10.1
  script:
    - apt update
    - apt install -y postgresql-client git bundler rake libxml2-dev libxslt-dev libicu-dev default-libmysqlclient-dev libpq-dev nodejs
    - "sed -i -e 's/host: mysql/host: mariadb/' config/database.yml"
    - bundle install --path vendor/bundle
    - bundle exec rake db:migrate
    - bundle exec rake db:oar:seed
    - bundle exec rspec spec/
  
deb-for-jessie: &deb-for-jessie
  image: debian:jessie
  stage: deb
  tags:
  - docker
  script:
  - apt-get update
  - apt-get install -y lsb-release git git-core bundler rake libxml2-dev ruby-dev libicu-dev build-essential libmysqlclient-dev libxslt-dev libpq-dev nodejs curl pkg-config
  - bundle install --path vendor/bundle
  - bundle exec rake package:build:debian 
  artifacts:
    paths:
    - pkg/g5k-api*.deb
    expire_in: '1 day'

deb-for-stretch:
  <<: *deb-for-jessie
  image: debian:stretch
  script:
  - apt-get update
  - apt-get install -y lsb-release git git-core bundler rake libxml2-dev ruby-dev libicu-dev build-essential default-libmysqlclient-dev libxslt-dev libpq-dev nodejs curl pkg-config
  - bundle install --path vendor/bundle
  - bundle exec rake package:build:debian
  allow_failure: true

push-jessie-package-v3: &push-jessie-package-v3
  stage: deploy
  # tags must be 'packages' so that we use the runner on packages.grid5000.fr
  tags:
    - packages
  only: # we only execute this job for tagged commits on the master branch
    refs:
      - tags
      - master
    variables:
      - $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
  dependencies:
    - deb-for-jessie
  script:
    - "[ $CI_COMMIT_REF_NAME = 'master' ] && g5k-deploy-files --files 'pkg/g5k-api_*.deb' --directory deb/g5k-api/jessie/v3"

push-jessie-package-devel: &push-jessie-package-devel
  <<: *push-jessie-package-v3
  script:
    - "[ $CI_COMMIT_REF_NAME = 'devel' ] && g5k-deploy-files --files 'pkg/g5k-api_*.deb' --directory deb/g5k-api/jessie/devel"
  only: # we only execute this job for tagged commits on the master branch
    refs:
      - tags
      - devel
    variables:
      - $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
    
push-stretch-package-v3:
  <<: *push-jessie-package-v3
  dependencies:
    - deb-for-stretch
  script:
    - "[ $CI_COMMIT_REF_NAME = 'master' ] && g5k-deploy-files --files 'pkg/g5k-api_*.deb' --directory deb/g5k-api/stretch/v3"

push-stretch-package-devel:
  <<: *push-jessie-package-devel
  dependencies:
    - deb-for-stretch
  script:
    - "[ $CI_COMMIT_REF_NAME = 'devel' ] && g5k-deploy-files --files 'pkg/g5k-api_*.deb' --directory deb/g5k-api/stretch/devel"
  
