# You'll need to activate pipelines for this file to have any effect
# in gitlab, go to Settings -> General -> Permissions -> Pipeline

stages:
 - test
 - deb
 - deploy

test-for-buster: &test-for-buster
  image: debian:buster
  stage: test
  services:
    - name: mariadb:10.3
      alias: mysql
    - name: postgres
  tags:
    - grid5000-docker
  variables:
    RAILS_ENV: test
    MYSQL_ROOT_PASSWORD: uheiN4pe
    MYSQL_DATABASE: g5kapi_test
    MYSQL_USER: g5kapi
    MYSQL_PASSWORD: Pe9IeCei
    POSTGRES_USER: oar
    POSTGRES_PASSWORD: oar
    POSTGRES_DB: oar2_test
  script:
    - apt-get update && apt-get -y --no-install-recommends install devscripts build-essential equivs libssl-dev
    - mk-build-deps -ir -t 'apt-get -y --no-install-recommends'
    - gem install bundler -v 2.1.4
    - bundle install --path vendor/bundle
    - bundle exec rake db:migrate
    - bundle exec rake db:oar:seed
    - bundle exec rspec spec/
  artifacts:
    when: on_failure
    paths:
    - log/test.log
    expire_in: '1 week'
  coverage: '/\(\d+.\d+\%\) covered/'
  except:
    - tags

deb-for-buster: &deb-for-buster
  image: debian:buster
  stage: deb
  tags:
  - grid5000-docker
  script:
    - apt-get update && apt-get -y --no-install-recommends install devscripts build-essential equivs libssl-dev
    - mk-build-deps -ir -t 'apt-get -y --no-install-recommends'
    - gem install bundler -v 2.1.4
    - apt-get install -y curl pkg-config
    - dpkg-buildpackage
    - mkdir pkg
    - cp ../*deb pkg/
  artifacts:
    paths:
    - pkg/g5k-api*.deb
    expire_in: '1 day'
  except:
    - tags

.push-packages-script: &push-packages-script |
  echo "Request to push for debian version ${TARGET_DEBIAN_VERSION} for branch ${TARGET_G5K_API_VARIANT}"
  g5k-deploy-files --only-if-tag '^v\d+\.\d+\.\d+' --files 'pkg/g5k-api_*.deb' --directory deb/g5k-api/${TARGET_DEBIAN_VERSION}/${TARGET_G5K_API_VARIANT}

push-buster-package-v3: &push-buster-package-v3
  stage: deploy
  when: manual
  allow_failure: false
  # tags must be 'packages' so that we use the runner on packages.grid5000.fr
  tags:
    - grid5000-packages
  only: # we only execute this job for tagged commits on the master branch
    - master
  dependencies:
    - deb-for-buster
  variables:
    TARGET_DEBIAN_VERSION: buster
    TARGET_G5K_API_VARIANT: v3
  script:
    - *push-packages-script

push-buster-package-v4: &push-buster-package-v4
  <<: *push-buster-package-v3
  variables:
    TARGET_DEBIAN_VERSION: buster
    TARGET_G5K_API_VARIANT: v4
  only:
    - devel

push-buster-package-devel: &push-buster-package-devel
  <<: *push-buster-package-v3
  variables:
    TARGET_DEBIAN_VERSION: buster
    TARGET_G5K_API_VARIANT: devel
  only:
    - devel
