Document: g5kapi
Title: Debian g5kapi Manual
Author: <insert document author here>
Abstract: This manual describes what g5kapi is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/g5kapi/g5kapi.sgml.gz

Format: postscript
Files: /usr/share/doc/g5kapi/g5kapi.ps.gz

Format: text
Files: /usr/share/doc/g5kapi/g5kapi.text.gz

Format: HTML
Index: /usr/share/doc/g5kapi/html/index.html
Files: /usr/share/doc/g5kapi/html/*.html


